### ISSUE TITLE
version of module named 'art' is wrong

### ISSUE THREAD

**Issue by thulx18** [TrustAIResearch/MLHospital#1]
在按照environment.yml配置了art==5.8后，运行mia_example.py，仍然报错No module named 'art.attacks'，试了其他几个版本任然有问题

**Comment by zhenglisec** [comment]
您好，感谢您提出的问题。经过检查，我们已经将environment.yml文件中的art==5.8删除，第187行的adversarial-robustness-toolbox即为art，请重新按照新的environment.yml配置即可。
