### ISSUE TITLE
Problems about the code

### ISSUE THREAD

**Issue by chihhsunlin** [TrustAIResearch/MLHospital#3]
In MLHospital/mlh/data_preprocessing/data_loader.py , the line 44 and the line 68 are same, is it correct?

In MLHospital/mlh/examples/mia_example.py , why the line 94 and the line 98 use the same data source {args.training_type} ?
If I select the training_type=PATE when I train a shadow model, the target model should be as the real data, is it right?

Thanks

**Comment by TrustAIResearch** [comment]
Hi,

Thanks for reaching out.

For the first question: 
We have modified the code. Line 68 should be:
`dataset in configs.SUPPORTED_IMAGE_DATASETS_ATTRIBUTE_INFERENCE`

For the second question:
The target and shadow models can be trained with different methods, e.g., the target model is trained without defense and the shadow model is trained with PATE.

When conducting the MIA, you can modify the mia_example.py to fit your needs, e.g., `training_type=Normal` for the target model and `training_type=PATE` for the shadow model.
